name: Hello world
on: #["push","pull_request"]
 push:
  branches:
    - main
    - master
    - release/**
 pull_request:
  branches:
    - m
jobs:
  build:
    runs-on: ubuntu-latest ##virtual machine to run all the jobs
    steps:
      - name: Build step
        run: echo "Build Step"
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        run: echo "this is test"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy
        run: echo "this is deploy"
