name: Hello world
on: workflow_dispatch #only manually
jobs:
  hello:
    runs-on: ubuntu-latest ##virtual machine to run all the jobs
    steps:
      - name: Build step
        run: |
         echo "this is line one"
         ls
