name: github actions
on: push
jobs:
  actions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print index html
        run: cat index.html