name: Inputs Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

      artifact-tag:
        description: "Choose the git tag to deploy"
        required: true
        type: string

jobs:
  input-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the app
        run: |
          echo "Deploying application to ${{ inputs.environment }}"
          echo "Artifact Tag: ${{ inputs['artifact-tag'] }}"
          echo "this is triggered by ${{ github.actor }}"
          echo "the repo name is ${{ github.repository }}"
          
      - name: print all variables under github
        run: echo "${{ toJson(github)}}"